<?php

/**
 * @file
 * Contains shopify_customers.module.
 */

use Drupal\Core\Routing\RouteMatchInterface;

/**
 * Implements hook_help().
 */
function shopify_customers_help($route_name, RouteMatchInterface $route_match) {
  switch ($route_name) {
    // Main module help for the shopify_customers module.
    case 'help.page.shopify_customers':
      $output = '';
      $output .= '<h3>' . t('About') . '</h3>';
      $output .= '<p>' . t('Import Shopify user into Drupal Commerce') . '</p>';
      return $output;

    default:
  }
}
